data_dir: "./data"
tf_dir: "./TFs"
dataset_name: "endocrinogenesis_day15"
save_dir: "./output"
model_dir: "./model"
n_top_genes: 2000
min_shared_counts: 20
n_pcs: 30
n_neighbors: 30
embedding_dim: 128
hidden_dim: 256
heads: 1
num_layers: 1
vel_num_layers: 1
time_num_layers: 8
dropout: 0.1
seed: 59510
epochs: 300
batch_size: 512
learning_rate: 0.00001
learning_rate_train: 0.00001
lambda_velocity: 0.000000001
lambda_steady: 0.000000001
lambda_scale: 0.1
lambda_smooth: 0.1
velocity_start: 100
init_tf_end: 100
init_self_end: 100
init_param_end: 300
scale_freeze_end: 500
steady_in_phase3: false
smooth_in_phase1: false
